import { Prisma } from "@prisma/client";

export const productSeeds: Prisma.ProductCreateManyInput[] = [
  {
    name: "チャーハンコンボ",
    price: 680,
    priceWithTax: 714,
    classification: "NEW",
    categoryId: 1,
  },
  {
    name: "牛肉ピーマン・マーボー弁当",
    price: 730,
    priceWithTax: 766,
    classification: "NEW",
    categoryId: 1,
  },
  {
    name: "特選中華弁当・四川",
    price: 780,
    priceWithTax: 819,
    classification: "NEW",
    categoryId: 1,
  },
  {
    name: "得トクプレート (3〜4人前)",
    price: 2980,
    priceWithTax: 3129,
    classification: "NORMAL",
    categoryId: 2,
  },
  {
    name: "欲バリプレート (3〜4人前)",
    price: 3980,
    priceWithTax: 4179,
    classification: "NORMAL",
    categoryId: 2,
  },
  {
    name: "自慢・焼餃子 (5ヶ)",
    price: 180,
    priceWithTax: 189,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "ゴマ付きだんご (2ヶ)",
    price: 240,
    priceWithTax: 252,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "はちみつ揚げパン",
    price: 240,
    priceWithTax: 252,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "香港フライドポテト",
    price: 280,
    priceWithTax: 294,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "海老春巻 (2本)",
    price: 280,
    priceWithTax: 294,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "ポークしゅうまい (5ヶ)",
    price: 280,
    priceWithTax: 294,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "カリカリ・花巻 (揚げ) (3ヶ)",
    price: 280,
    priceWithTax: 294,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "ふわふわ・花巻 (蒸し) (3ヶ)",
    price: 280,
    priceWithTax: 294,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "芒果ジュース",
    price: 330,
    priceWithTax: 346,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "西瓜ジュース",
    price: 330,
    priceWithTax: 346,
    classification: "NEW",
    categoryId: 3,
  },
  {
    name: "杭州東坡肉 (豚の角煮)",
    price: 380,
    priceWithTax: 399,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "若鶏のからあげ (6ヶ)",
    price: 480,
    priceWithTax: 504,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "バンバンジーサラダ",
    price: 480,
    priceWithTax: 504,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "海老マヨネーズ",
    price: 580,
    priceWithTax: 609,
    classification: "NORMAL",
    categoryId: 3,
  },
  {
    name: "マーボー豆腐",
    price: 480,
    priceWithTax: 504,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "辛口・本格四川マーボー豆腐",
    price: 480,
    priceWithTax: 504,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "若鶏の甘酢しょうが",
    price: 480,
    priceWithTax: 504,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "牛肉とピーマンの細切り炒め",
    price: 580,
    priceWithTax: 609,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "からあげの黒酢ソース",
    price: 580,
    priceWithTax: 609,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "ホイコーロウ",
    price: 580,
    priceWithTax: 609,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "夏の特製酢豚",
    price: 680,
    priceWithTax: 714,
    classification: "NEW",
    categoryId: 4,
  },
  {
    name: "海老野菜炒め",
    price: 680,
    priceWithTax: 714,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "角切り牛肉ピーマンのカシューナッツ炒め",
    price: 680,
    priceWithTax: 714,
    classification: "NEW",
    categoryId: 4,
  },
  {
    name: "海老のチリソース",
    price: 780,
    priceWithTax: 819,
    classification: "NORMAL",
    categoryId: 4,
  },
  {
    name: "チャーハン",
    price: 480,
    priceWithTax: 504,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "旬の中華丼",
    price: 680,
    priceWithTax: 714,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "旬の五目焼そば",
    price: 680,
    priceWithTax: 714,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "上海風・蟹入り天津飯",
    price: 780,
    priceWithTax: 819,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "桜海老の台湾焼ビーフン",
    price: 680,
    priceWithTax: 714,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "大海老の留学あんかけご飯",
    price: 680,
    priceWithTax: 714,
    classification: "NEW",
    categoryId: 5,
  },
  {
    name: "五目冷し中華",
    price: 680,
    priceWithTax: 714,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "海鮮・皿うどん",
    price: 780,
    priceWithTax: 819,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "ライス",
    price: 180,
    priceWithTax: 189,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "大ライス",
    price: 230,
    priceWithTax: 241,
    classification: "NORMAL",
    categoryId: 5,
  },
  {
    name: "小ライス",
    price: 100,
    priceWithTax: 105,
    classification: "NORMAL",
    categoryId: 5,
  },
];
